name: Bug report
description: Report a reproducible bug in Chrome Activity Reader
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Clear and concise bug summary.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps.
      placeholder: |
        1. Open ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: chrome_version
    attributes:
      label: Chrome version
      placeholder: e.g. 134.0.x
    validations:
      required: true

  - type: input
    id: extension_version
    attributes:
      label: Extension version
      placeholder: e.g. 0.1.1
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Logs / screenshots / artifacts
      description: Paste console errors, attach screenshots, or list artifact paths.
